### ISSUE TITLE
Propose a cleaner way of pasting the system info on bug reports

### ISSUE THREAD

**Issue by CodingSpiderFox** [elementary/feedback#18] opened 2019-12-16 06:23 UTC
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

When creating a bug on elementary OS repositories, the issue template asks to: 

```
## Platform Information
<!--
Please share a screenshot of the System Settings > About screen.
If you can't please share:
 - OS: [e.g. elementary OS]
 - OS Version [e.g. Juno]
 - Hardware info
```

As uploading and serving images uses more resources than simple text, I would suggest to also provide a command with which you can get the information that is displayed in the GUI as simple text from the command line

**Comment by peteruithoven** [comment] 2020-01-31 21:44
Kind of related to: https://github.com/elementary/switchboard-plug-about/issues/47

(Personally I'm against people having to use the terminal for these things.)

**Comment by danrabbit** [comment] 2020-04-29 00:21
Gonna close this as a duplicate of #9

**Closed by danrabbit** 2020-04-29 00:21 UTC
