### ISSUE TITLE
The feedback app won't go to the screen where you finish submitting the feedback and type details of the issue

### ISSUE THREAD

**Issue by CuriousCoconut** [elementary/feedback#115] opened 2024-11-19 23:47 UTC
### What Happened?

When opening the feedback app and clicking on an option like "dock" and then clicking the send feedback button the app closes and nothing else happens. It never gets to the screen where you can actually submit feedback.

### Steps to Reproduce

Opened the feedback app, clicked on "dock" and then clicked on "send feedback" button. App just disappears/closes and the page to type details of the issue etc never shows up.

### Expected Behavior

It should go to a screen where you can type out details of the issue and finish submitting feedback.

### OS Version

8.x (Early Access)

### Session Type

Classic Session (X11, This is the default)

### Software Version

Latest release (I have run all updates)

**Comment by ryonakano** [comment] 2024-11-20 11:55
I'm on OS 8 RC with Classic Session but I can't reproduce your issue. A few questions:

- Which Web browser are you using? Web, the default one, or another third-party browser?
- Is it possible to run your browser directly?

**Comment by CuriousCoconut** [comment] 2024-11-20 11:59
I didn't install it I just used the try option and that's where the
feedback app isn't working maybe you're using an installed copy?

**Comment by ryonakano** [comment] 2024-11-20 12:05
Yes, I'm using an installed copy of OS. I can now reproduce your issue on the live image of OS.

However, let's close this in favor of https://github.com/elementary/triage/issues/600, this issue is not due to Feedback app itself but it's due to the OS itself.

**Closed by ryonakano** 2024-11-20 12:05 UTC
Labels: Status: Incomplete

**Comment by CuriousCoconut** [comment] 2024-11-20 12:06
Ok, thank you.
